# Generated by Django 6.0.6 on 2026-06-26 14:12

import certificados.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=255)),
                ('excel', models.FileField(upload_to=certificados.models.ruta_excel)),
                ('plantilla', models.ImageField(upload_to=certificados.models.ruta_plantilla)),
                ('texto_x', models.PositiveIntegerField(help_text='Posicion X en pixeles de la plantilla')),
                ('texto_y', models.PositiveIntegerField(help_text='Posicion Y en pixeles de la plantilla')),
                ('margen_izquierdo', models.PositiveIntegerField(default=40)),
                ('margen_derecho', models.PositiveIntegerField(default=40)),
                ('tamano_fuente', models.PositiveIntegerField(default=40)),
                ('tamano_fuente_min', models.PositiveIntegerField(default=18)),
                ('color_texto', models.CharField(default='#1a1a1a', max_length=7)),
                ('fuente', models.CharField(default='Helvetica-Bold', max_length=50)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('generado', 'Generado'), ('error', 'Error')], default='borrador', max_length=10)),
                ('total_certificados', models.PositiveIntegerField(default=0)),
                ('zip_resultado', models.FileField(blank=True, null=True, upload_to='lotes/resultados/')),
                ('mensaje_error', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
