# Generated by Django 6.0.6 on 2026-06-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='procesados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lote',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('procesando', 'Procesando'), ('generado', 'Generado'), ('error', 'Error')], default='borrador', max_length=10),
        ),
    ]
