# Generated by Django 6.0.6 on 2026-06-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0003_lote_generado_en_lote_generado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='archivos_expirados',
            field=models.BooleanField(default=False, help_text='Los PDF/ZIP generados se borraron por antiguedad; el registro del lote se conserva'),
        ),
    ]
