# Generated by Django 6.0.6 on 2026-07-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0004_lote_archivos_expirados'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='qr_activo',
            field=models.BooleanField(default=False, help_text='Incluir un codigo QR en el certificado'),
        ),
        migrations.AddField(
            model_name='lote',
            name='qr_contenido',
            field=models.CharField(blank=True, help_text='Texto o URL que codificara el QR', max_length=500),
        ),
        migrations.AddField(
            model_name='lote',
            name='qr_tamano',
            field=models.PositiveIntegerField(default=120, help_text='Lado del QR en pixeles'),
        ),
        migrations.AddField(
            model_name='lote',
            name='qr_x',
            field=models.PositiveIntegerField(blank=True, help_text='Posicion X (centro) en pixeles de la plantilla', null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='qr_y',
            field=models.PositiveIntegerField(blank=True, help_text='Posicion Y (centro) en pixeles de la plantilla', null=True),
        ),
    ]
