# Generated by Django 6.0.6 on 2026-07-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0005_lote_qr_activo_lote_qr_contenido_lote_qr_tamano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='qr_contenido',
            field=models.CharField(blank=True, help_text='Texto o URL que codificara el QR. Puede ser fijo para todos, o incluir las variables {nombre}, {curso} y {codigo} (codigo unico autogenerado por participante) para que cada certificado tenga un QR distinto.', max_length=500),
        ),
    ]
