# Generated by Django 6.0.6 on 2026-08-01 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0006_alter_lote_qr_contenido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('valor_original', models.CharField(blank=True, max_length=500)),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='certificados.lote')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
    ]
