# Generated by Django 6.0.6 on 2026-08-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0008_poblar_estudiantes_desde_excel'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='nombre_normalizado',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
